### ISSUE TITLE
ModuleNotFoundError: No module named 'comfy.ldm.flux.redux'

### ISSUE THREAD

**Issue by fandongminghitmt** [tanglup/Comfyui_Flux_Style_Adjust#2]
PS C:\ML_TEST\ComfyUI> python .\main.py
[START] Security scan
[DONE] Security scan
## ComfyUI-Manager: installing dependencies done.
** ComfyUI startup time: 2024-11-29 14:18:07.256523
** Platform: Windows
** Python version: 3.11.9 (tags/v3.11.9:de54cf5, Apr  2 2024, 10:12:12) [MSC v.1938 64 bit (AMD64)]
** Python executable: C:\Users\user\AppData\Local\Programs\Python\Python311\python.exe
** ComfyUI Path: C:\ML_TEST\ComfyUI
** Log path: C:\ML_TEST\ComfyUI\comfyui.log

Prestartup times for custom nodes:
   1.5 seconds: C:\ML_TEST\ComfyUI\custom_nodes\ComfyUI-Manager

Total VRAM 24564 MB, total RAM 130845 MB
pytorch version: 2.5.1+cu124
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 4090 : cudaMallocAsync
Using pytorch cross attention
[Prompt Server] web root: C:\ML_TEST\ComfyUI\web
C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\kornia\feature\lightglue.py:44: FutureWarning: `torch.cuda.amp.custom_fwd(args...)` is deprecated. Please use `torch.amp.custom_fwd(args..., device_type='cuda')` instead.
  @torch.cuda.amp.custom_fwd(cast_inputs=torch.float32)
[Crystools INFO] Crystools version: 1.21.0
[Crystools INFO] CPU: Intel(R) Core(TM) i9-14900KS - Arch: AMD64 - OS: Windows 10
[Crystools INFO] Pynvml (Nvidia) initialized.
[Crystools INFO] GPU/s:
[Crystools INFO] 0) NVIDIA GeForce RTX 4090
[Crystools INFO] 1) NVIDIA GeForce RTX 4090
[Crystools INFO] NVIDIA Driver: 566.14
### ComfyUI Revision: 2841 [89861512] | Released on '2024-11-19'
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/alter-list.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/model-list.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/github-stats.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/extension-node-map.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/custom-node-list.json
--------------
 ### Mixlab Nodes: Loaded
json_repair## OK
ChatGPT.available True
edit_mask.available True
## clip_interrogator_model not found: C:\ML_TEST\ComfyUI\models\clip_interrogator\Salesforce\blip-image-captioning-base, pls download from https://huggingface.co/Salesforce/blip-image-captioning-base
ClipInterrogator.available True
## zh_en_model not found: C:\ML_TEST\ComfyUI\models\prompt_generator\opus-mt-zh-en, pls download from https://huggingface.co/Helsinki-NLP/opus-mt-zh-en/tree/main
PromptGenerate.available True
ChinesePrompt.available True
RembgNode_.available True
TripoSR.available
MiniCPMNode.available
Scenedetect.available
FishSpeech.available
SenseVoice.available
Whisper.available False
fal-client## OK
FalVideo.available
 --------------
Traceback (most recent call last):
  File "C:\ML_TEST\ComfyUI\nodes.py", line 2024, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\ML_TEST\ComfyUI\custom_nodes\Comfyui_Flux_Style_Adjust\__init__.py", line 1, in <module>
    from .nodes import StyleModelAdvancedApply
  File "C:\ML_TEST\ComfyUI\custom_nodes\Comfyui_Flux_Style_Adjust\nodes.py", line 3, in <module>
    from comfy.ldm.flux.redux import ReduxImageEncoder
ModuleNotFoundError: No module named 'comfy.ldm.flux.redux'

Cannot import C:\ML_TEST\ComfyUI\custom_nodes\Comfyui_Flux_Style_Adjust module for custom nodes: No module named 'comfy.ldm.flux.redux'
PyTorch version 2.5.1+cu124 available.
TensorFlow version 2.12.0 available.
JAX version 0.4.30 available.
C:\ML_TEST\ComfyUI\custom_nodes\ComfyUI_MaskGCT-main\models\tts\maskgct\g2p\sources\g2p_chinese_model\poly_bert_model.onnx
WAS Node Suite: OpenCV Python FFMPEG support is enabled
WAS Node Suite Warning: `ffmpeg_bin_path` is not set in `C:\ML_TEST\ComfyUI\custom_nodes\was-node-suite-comfyui\was_suite_config.json` config file. Will attempt to use system ffmpeg binaries if available.
WAS Node Suite: Finished. Loaded 218 nodes successfully.

        "Your time is limited, don't waste it living someone else's life." - Steve Jobs

Import times for custom nodes:
   0.0 seconds: C:\ML_TEST\ComfyUI\custom_nodes\websocket_image_save.py
   0.0 seconds: C:\ML_TEST\ComfyUI\custom_nodes\ComfyUI-ZeroShot-MTrans
   0.0 seconds: C:\ML_TEST\ComfyUI\custom_nodes\ComfyUI_IPAdapter_plus
   0.0 seconds (IMPORT FAILED): C:\ML_TEST\ComfyUI\custom_nodes\Comfyui_Flux_Style_Adjust
   0.0 seconds: C:\ML_TEST\ComfyUI\custom_nodes\ComfyUI_essentials
   0.0 seconds: C:\ML_TEST\ComfyUI\custom_nodes\ComfyUI-Advanced-ControlNet
   0.2 seconds: C:\ML_TEST\ComfyUI\custom_nodes\ComfyUI-3D-MeshTool
   0.3 seconds: C:\ML_TEST\ComfyUI\custom_nodes\ComfyUI-Crystools
   0.7 seconds: C:\ML_TEST\ComfyUI\custom_nodes\ComfyUI-Manager
   1.0 seconds: C:\ML_TEST\ComfyUI\custom_nodes\was-node-suite-comfyui
   3.1 seconds: C:\ML_TEST\ComfyUI\custom_nodes\comfyui-mixlab-nodes
   3.2 seconds: C:\ML_TEST\ComfyUI\custom_nodes\ComfyUI_MaskGCT-main

Starting server

To see the GUI go to: http://127.0.0.1:8188

**Comment by tanglup** [comment]
Need to update comfyui

**Comment by bosima** [comment]
can remove this import
